### ISSUE TITLE
testing, testing

### ISSUE THREAD

**Issue by Badpoolinator** [Spekktrum-Studio/portal-system-failure-issue-tracker#3] opened 2024-10-04 21:46 UTC
everything seems to be in order

alright gordon your suit should keep your comfortable through all this, the specimen will be delivered to you in a few moments. if you'd be so good as to climb up and start the rotors, we can bring the anti mass spectrometer to 80% and hold it there until the carrier arrives.

**Comment by PRYZMwubs** [comment] 2024-10-04 21:49
not a bug won't fix + you're stupid

L bozo
![Realistic_Bomb](https://github.com/user-attachments/assets/df206774-50d0-4071-8fbe-1e9a6cd34942)

**Comment by Badpoolinator** [comment] 2024-10-04 21:50
wow bro, that is bang out of order 😔

**Closed** 2024-10-04 21:50 UTC
Labels: Wont Fix, Not a bug

**Comment by SprocketTools** [comment] 2024-10-05 00:22
![NightysTank](https://github.com/user-attachments/assets/964a7fa3-58d9-417f-986e-55bc2142dd56)
